common:
  timezone: "America/Denver"
  gps_sample_interval: 300          # Expected seconds between GPS
  gps_sample_interval: 60           # Expected seconds between Accelerometer 
  excluded_devices: [841, 1005] 


io:
  format: "multiple_files"
  gps_directory: "data/raw/RB_22/gps"
  accelerometer_directory: "data/raw/RB_22/accelerometer"
  labeled_data_path: "data/raw/RB_22/labeled/gps_observations_2022.csv"
  file_pattern: "*.csv"

validation:
  start_datetime: "2022-01-15 00:00:00"
  end_datetime: "2022-03-22 23:59:59"
  lat_min: -90
  lat_max: 90
  lon_min: -180
  lon_max: 180
  accel_min: -41
  accel_max: 41
  temp_min: -99
  temp_max: 99
  min_satellites: 0
  max_dop: 10.0
  COVERAGE_THRESHOLD: 70            # Minimum ratio of (actual / expected) GPS data needed to include the device

features:
  enable_axis_features: true        # Compute features for each axes
  enable_magnitude_features: true   # Compute features for the magnitudes
  feature_types:
    - "BASIC_STATS"                 # Mean, variance of the window
    - "ZERO_CROSSINGS"              # Count of transitions from - to + or + to -
    - "PEAK_FEATURES"               # Statistics covering the peaks of the window
    - "ENTROPY"                     # Compute signal entropy features
    - "CORRELATION"                 # Compute correlation between axes
    # - "SPECTRAL"                    # Compute frequency domain features
 
labels:
  # labeled_agg_method: "MODE"        # The most frequent activity in the window
  labeled_agg_method: "RAW"           # The activity at the end of the window
  # labeled_agg_method: "PERCENTILE"  # A weighted choice of activity

  valid_activities:
    - "Resting"
    - "Grazing"
    - "Traveling"
    - "Fighting"
    - "Scratching"
    - "Drinking"
    - "Mineral"

testing:
  device_id: 824  # Test with single cow  