common:
  dataset_name: RB_22
  timezone: "America/Denver"
  gps_sample_interval: 300          # Expected seconds between GPS
  accel_sample_interval: 60           # Expected seconds between Accelerometer 
  # excluded_devices: [841, 1005, 1021, 1006] 
  excluded_devices: [841, 1005] 
  random_seed: 123


io:
  gps_directory: "data/raw/RB_22/gps"
  accelerometer_directory: "data/raw/RB_22/accelerometer"
  labeled_data_path: "data/raw/RB_22/labeled/gps_observations_2022.csv"
  cow_info_path: "data/raw/RB_22/cow_info/Aggregate_collar_info.xlsx"

  # processed_data_path: "data/processed/RB_22/all_cows_labeled_mode.csv"
  processed_data_path: "data/processed/RB_22/all_cows_labeled.csv"
  

validation:
  start_datetime: "2022-01-15 00:00:00"
  end_datetime: "2022-03-23 00:00:00"
  # Minimum ratio of (actual / expected) GPS data needed to include the device
  COVERAGE_THRESHOLD: 70

  # New validation rules structure
  validation_rules:
    # GPS validation rules
    latitude:
      min_value: -90.0
      max_value: 90.0
      is_required: true
      filter_invalid: false

    longitude:
      min_value: -180.0
      max_value: 180.0
      is_required: true
      filter_invalid: false

    dop:
      max_value: 10.0
      is_required: true
      filter_invalid: true # FILTERING HERE

    satellites:
      min_value: 0
      is_required: true
      filter_invalid: false

    altitude:
      min_value: 0
      max_value: 1715
      is_required: false
      filter_invalid: false

    temperature_gps:
      min_value: -99
      max_value: 99
      is_required: true
      filter_invalid: false

    # Accelerometer validation rules
    x:
      min_value: -41
      max_value: 41
      is_required: true
      filter_invalid: false

    y:
      min_value: -41
      max_value: 41
      is_required: true
      filter_invalid: false

    z:
      min_value: -41
      max_value: 41
      is_required: true
      filter_invalid: false

    temperature_acc:
      min_value: -99
      max_value: 99
      is_required: true
      filter_invalid: false

features:
  enable_axis_features: true        # Compute features for each axes
  enable_magnitude_features: true   # Compute features for the magnitudes
  feature_types:
    - "BASIC_STATS"                 # Mean, variance of the window
    # - "ZERO_CROSSINGS"              # Count of transitions from - to + or + to -
    # - "PEAK_FEATURES"               # Statistics covering the peaks of the window
    # - "ENTROPY"                     # Compute signal entropy features
    # - "CORRELATION"                 # Compute correlation between axes
    # - "SPECTRAL"                    # Compute frequency domain features
 
labels:
  # labeled_agg_method: "MODE"        # The most frequent activity in the window
  labeled_agg_method: "RAW"           # The activity at the end of the window
  # labeled_agg_method: "PERCENTILE"  # A weighted choice of activity NOT IMPLEMENTED
  valid_activities:
    - "Resting"
    - "Grazing"
    - "Traveling"
    - "Fighting"
    - "Scratching"
    - "Drinking"
    - "Mineral"

analysis:
  mode: "LOOCV"     # Do LOOCV on the target dataset. 
  # mode: "PRODUCT"   # predict activity labels for a full dataset
  target_dataset: "data/processed/RB_22/all_cows_labeled.csv"  # Required The dataset to make predictions on
  # training_info_path: "data/analysis_results/hmm/FinalModels/RB_22_Paper_Model/trained_model.rds" # No CV, no filter cows, no covariate.


  r_executable: "C:/Program Files/R/R-4.4.1/bin/Rscript.exe"
  # r_executable: "C:/Program Files/R/R-4.4.3/bin/Rscript.exe"
  # r_executable: "C:/Program Files/R/R-4.3.0/bin/Rscript.exe"

  
  
  
  
  ########## TEMP ONLY FOR BAYSES OPT I NEED SLEEP
  # output_dir: "data/analysis_results"



  cv_results: "data/cv_results/RB_22"
  models: "data/models/RB_22"
  predictions: "data/predictions/RB_22"


  day_only: false

  hmm:
    enabled: false
    time_covariate: false

    states: # The states to use in the HMM
      - "Grazing"
      - "Resting"
      - "Traveling"
    features:
      - name: "step" # Powerful
        dist: null
        dist_type: "regular"
      - name: "angle" # Ok
        dist: null
        dist_type: "circular"
      - name: "magnitude_mean" # Powerful
        dist: null 
        dist_type: "regular"
      # - name: "x_crest_factor" # OK
      #   dist: null
      #   dist_type: "regular"
      # - name: "x_peak_to_peak" # not impressed
      #   dist: null
      #   dist_type: "regular"
      # - name: "y_peak_to_peak" # Pretty good
      #   dist: null
      #   dist_type: "regular"
      # - name: "x_impulse_factor" # Not Impressive
      #   dist: null
      #   dist_type: "regular"
      - name: "magnitude_var" # Ok
        dist: null
        dist_type: "regular"

      # Can kindof add covariates here. They work but break some other reports like transition matrices. 
      # Need to manaually update the fitHMM formula argument from ~1 to ~temperature_gps  
      # - name: "temperature_gps"  # Add the covariate
      #   dist: null
      #   dist_type: "covariate"  # New dist_type for covariates

    options:
      show_dist_plots: true
      remove_outliers: true   # From the plots
      show_full_range: true
      show_correlation: true
      number_of_retry_fits: 1 # 1
      distributions:
        regular:
          - "LOGNORMAL"
          - "GAMMA"
          # - "WEIBULL" # This does not work. Needs To be debugged.
          - "NORMAL"
          - "EXPONENTIAL"
        circular:
          - "VONMISES"
          - "WRAPPEDCAUCHY"

  lstm:
    enabled: true
    
    ops: false


    ################ Warning these two will SIGNIFICANTLY increase runtime to find parameters 
    # BAYESIAN Optimization
    bayes_opt: true                # Whether to use Bayesian optimization 
    bayes_opt_n_calls: 20          # Number of evaluations to perform
    bayes_opt_resume: true         # Whether to resume from previous optimization
    bayes_opt_fast_eval: true      # Use faster evaluation during optimization

    # GRID SEARCH
    hyperparams_search: false   # Whether to run hyperparameter search
    hyperparams_sample: false   # Whether to sample a subset of parameters for quick testing

    states: # The states to use in the LSTM
      - "Grazing"
      - "Resting"
      - "Traveling"
      # - "Drinking"
      # - "Fighting"
      # - "Mineral"
    features:
      - "step"
      - "angle"
      - "magnitude_mean"
      - "magnitude_var"
      # - x_mean
      # - y_mean
      # - z_mean
      # - utm_easting
      # - utm_northing
      # - "x_mean"
      # - "x_var"
      # - "y_mean"
      # - "y_var"
      # - "z_mean"
      # - "z_var"
      # - "pct_of_day"
    # max_length: 'daily'
    # max_length: 20
    max_time_gap: 960
    epochs: 1000
    cows_per_cv_fold: 1

    # max_length: 36
    # batch_size: 32

    # OPO cv=2
    # ===== OVERALL RESULTS =====
    # Total accuracy: 0.8170
    # Grazing accuracy: 0.7291 (n=203)
    # Resting accuracy: 0.8836 (n=232)
    # Traveling accuracy: 0.8696 (n=46)

    ################### OPO BO Paper parameters
    max_length: 288
    batch_size: 5
    initial_lr: 0.0007918
    decay_steps: 3704
    decay_rate: 0.1
    clipnorm: 1.2775850
    patience: 37
    min_delta: 0.0001
    reg_val: 0.0000038
    # max_length: 271
    # batch_size: 2
    # initial_lr: 0.0001000
    # decay_steps: 3188
    # decay_rate: 0.7066770
    # clipnorm: 1.0862404
    # patience: 60
    # min_delta: 0.0001000
    # reg_val: 0.0000125


    ################### OPS BO Paper parameters
    # max_length: 184
    # batch_size: 32
    # initial_lr: 0.0079165
    # decay_steps: 4255
    # decay_rate: 0.2829337
    # clipnorm: 0.4411081
    # patience: 57
    # min_delta: 0.0000017
    # reg_val: 0.0000139


visuals:
  # predictions_path: 'data/analysis_results/hmm/PRODUCT/Preds_22_to_22_20250220_202010/predictions.csv'
  # predictions_path: 'data/analysis_results/hmm/PRODUCT/RB_22_20250302_185749/predictions.csv' # Good
  # predictions_path: 'data/analysis_results/hmm/FinalPredictions/RB_22_Paper_Model_Preds/predictions.csv' 
  # predictions_path: 'data/analysis_results/hmm/FinalPredictions/RB_Paper_Model_Preds_logmagvar/predictions.csv'
  
  
  # predictions_path: 'data/predictions/RB_22/HMM/predictions.csv'
  predictions_path: 'data/predictions/RB_22/LSTM/opo/predictions.csv'
  # predictions_path: 'data/predictions/RB_22/LSTM/ops/predictions.csv'

  # visuals_root_path: "data/visuals/RB_22/HMM"
  visuals_root_path: "data/visuals/LSTM/opo/"
  # visuals_root_path: "data/visuals/LSTM/ops/"

  radar:
    run: false
    extension: 'RadarPlots01/'
    show_night: true

  temperature_graph:
    run: true
    daynight: 'day' #'day' #'night' 'both'
    show_curve: true
    # extension: 'MDT_Plots/'
    minimum_required_values: 30
    show_table: true  # Whether to print a comparison table
    export_excel: false  # Whether to export results to Excel


    sample_size: 0.7

    terms:
    - hod
    - temp
    - time
    - time^2
    - time^3
    - time^4
    - hod:temp
    - hod:time
    - temp:time
    - temp:time^4
    - temp:time^2



  feature_dists:
    run: false

  convolution_surface:
    run: false

  moon_phases:
    run: false
    extension: 'moon_phases_plots/'

  domain:
    run: false
    implemented: true
    labeled_only: true

    # extension: 'cow_info_plots/'

  cow_info_graph:
    run: false
    implemented: true
    # extension: 'cow_info_plots/'

  heatmap:
    run: false
    # extension: 'heatmap/'

    filter_weigh_days: true
    weigh_days:
      - "2022-01-14"
      - "2022-01-25"
      - "2022-01-26"
      - "2022-02-22"
      - "2022-02-23"
      - "2022-03-22"
      - "2022-03-23"


    